### ISSUE TITLE
开发文档连接404了

### ISSUE THREAD

**Issue by stonelf** [Authing/web-sso-sample#1]
sample的readme中的开发文档连接https://docs.authing.cn/authing/quickstart/implement-sso-with-authing 点击过去404

**Comment by stonelf** [comment]
看了一下主页，似乎应该是 https://learn.authing.cn/authing/

**Comment by leinue** [comment]
> sample的readme中的开发文档连接https://docs.authing.cn/authing/quickstart/implement-sso-with-authing 点击过去404

哪个地区 404？我在中国正常诶。
![image](https://user-images.githubusercontent.com/2469688/65469580-89382a00-de9a-11e9-9569-4bfa7d766d9a.png)

**Comment by leinue** [comment]
![image](https://user-images.githubusercontent.com/2469688/65469675-d3211000-de9a-11e9-9e21-68d145d6370c.png)
加了这个

**Comment by leinue** [comment]
https://github.com/Authing/AuthingSSO
也可以看这个

**Comment by stonelf** [comment]
美国。目前已恢复。可能是边缘服务器回源故障导致。
